package mx.com.object;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import mx.com.dao.RegistroDAO;
import mx.com.dao.UsuarioDAO;
import mx.com.model.Registro;
import mx.com.model.Usuario;

/**
 *
 * @author abigail
 */

//ventana para el formulario de estado de autos
public class EstadoFrame extends javax.swing.JInternalFrame{

    Registro registro;//objeto de Registro
    RegistroDAO registroDao = new RegistroDAO();//objeto para hacer uso de los query para los registros
    Usuario usuarioEntrada, usuarioSalida;
    UsuarioDAO usuarioDao = new UsuarioDAO();
    /**
     * Creates new form Registro
     */
    public EstadoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblBoleto = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblPlacas = new javax.swing.JLabel();
        lblPropietario = new javax.swing.JLabel();
        lblCajon = new javax.swing.JLabel();
        lblEntrada = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        entrada = new javax.swing.JLabel();
        salida = new javax.swing.JLabel();
        boleto = new javax.swing.JTextField();
        marca = new javax.swing.JLabel();
        modelo = new javax.swing.JLabel();
        placas = new javax.swing.JLabel();
        color = new javax.swing.JLabel();
        propietario = new javax.swing.JLabel();
        btnVer = new javax.swing.JButton();
        cajon = new javax.swing.JLabel();
        lblBaja = new javax.swing.JLabel();
        lblusuarioAlta = new javax.swing.JLabel();
        lblusuarioBaja = new javax.swing.JLabel();
        alta = new javax.swing.JLabel();
        baja = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setMaximizable(true);
        setResizable(true);
        setTitle("Entrega de auto");

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(204, 255, 204));
        lblTitulo.setText("Estacionamiento Santa Fe");

        lblBoleto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBoleto.setForeground(new java.awt.Color(255, 255, 255));
        lblBoleto.setText("No. Boleto:");

        lblMarca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMarca.setForeground(new java.awt.Color(255, 255, 255));
        lblMarca.setText("Marca:");

        lblModelo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblModelo.setForeground(new java.awt.Color(255, 255, 255));
        lblModelo.setText("Modelo:");

        lblColor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblColor.setForeground(new java.awt.Color(255, 255, 255));
        lblColor.setText("Color:");

        lblPlacas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPlacas.setForeground(new java.awt.Color(255, 255, 255));
        lblPlacas.setText("Placas:");

        lblPropietario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPropietario.setForeground(new java.awt.Color(255, 255, 255));
        lblPropietario.setText("Nombre del propietario:");

        lblCajon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCajon.setForeground(new java.awt.Color(255, 255, 255));
        lblCajon.setText("Cajon:");

        lblEntrada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEntrada.setForeground(new java.awt.Color(255, 255, 255));
        lblEntrada.setText("Fecha y hora de entrada:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fecha y hora de salida:");

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total:");

        total.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        total.setForeground(new java.awt.Color(204, 204, 255));
        total.setText("-");

        entrada.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        entrada.setForeground(new java.awt.Color(204, 204, 255));
        entrada.setText("-");

        salida.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        salida.setForeground(new java.awt.Color(204, 204, 255));
        salida.setText("-");

        marca.setForeground(new java.awt.Color(204, 204, 255));
        marca.setText("-");

        modelo.setForeground(new java.awt.Color(204, 204, 255));
        modelo.setText("-");

        placas.setForeground(new java.awt.Color(204, 204, 255));
        placas.setText("-");

        color.setForeground(new java.awt.Color(204, 204, 255));
        color.setText("-");

        propietario.setForeground(new java.awt.Color(204, 204, 255));
        propietario.setText("-");

        btnVer.setText("Ver datos");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDatos(evt);
            }
        });

        cajon.setForeground(new java.awt.Color(204, 204, 255));
        cajon.setText("-");

        lblBaja.setBackground(new java.awt.Color(255, 255, 204));
        lblBaja.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblBaja.setForeground(new java.awt.Color(255, 255, 204));
        lblBaja.setText("Estado de auto");

        lblusuarioAlta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblusuarioAlta.setForeground(new java.awt.Color(255, 255, 255));
        lblusuarioAlta.setText("Usuario que dio la alta:");

        lblusuarioBaja.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblusuarioBaja.setForeground(new java.awt.Color(255, 255, 255));
        lblusuarioBaja.setText("Usuario que dio la baja:");

        alta.setForeground(new java.awt.Color(204, 204, 255));
        alta.setText("-");

        baja.setForeground(new java.awt.Color(204, 204, 255));
        baja.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(lblTitulo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblColor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblBoleto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boleto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblPlacas)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(placas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblModelo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(modelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblMarca)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEntrada)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblCajon)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cajon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblTotal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblusuarioAlta)
                                    .addComponent(lblusuarioBaja))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(salida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(baja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(alta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPropietario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBaja)
                                    .addComponent(propietario, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(btnVer)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBaja)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBoleto)
                    .addComponent(boleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelo)
                    .addComponent(modelo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlacas)
                    .addComponent(placas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColor)
                    .addComponent(color))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPropietario)
                    .addComponent(propietario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCajon)
                    .addComponent(cajon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEntrada)
                    .addComponent(entrada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(salida))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblusuarioAlta)
                    .addComponent(alta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblusuarioBaja)
                    .addComponent(baja))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(total))
                .addGap(20, 20, 20)
                .addComponent(btnVer)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //evento de accion para el boton de "Ver datos"
    private void btnVerDatos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDatos
        limpiar();
        if(!boleto.getText().isEmpty()){ //validamos que el usuario ingrese un numero de boleto         
            registro = registroDao.traerRegistro(Integer.parseInt(boleto.getText()));//traemos los registros de un auto de acuerdo al numero de boleto
            usuarioEntrada = usuarioDao.traerUsuarios(registro.getUsuarioEntrada());
            usuarioSalida = usuarioDao.traerUsuarios(registro.getUsuarioSalida());
            marca.setText(registro.getMarca());
            modelo.setText(registro.getModelo());
            placas.setText(registro.getPlacas());
            color.setText(registro.getColor());
            propietario.setText(registro.getPropietario());
            cajon.setText(String.format(" %d",registro.getCajon()));
            entrada.setText(registro.getEntrada().toString());
            if(registro.getSalida()!= null)
                salida.setText(registro.getSalida().toString());
            total.setText(String.format("$ %.2f ",registro.getTotal()));
            alta.setText(usuarioEntrada.getNombre());
            if(usuarioSalida!=null)
                baja.setText(usuarioSalida.getNombre());
        }else{
            JOptionPane.showMessageDialog(null, "Debe ingresar el Número de boleto");//si no hay registros, se le informa al usuario
        }
    }//GEN-LAST:event_btnVerDatos
    
    //metodo para limpiar los valores
    private void limpiar(){
        //boleto.setText("");
        marca.setText("");
        modelo.setText("");
        placas.setText("");
        color.setText("");
        propietario.setText("");
        cajon.setText("");
        entrada.setText("");
        salida.setText("");
        total.setText("");
        alta.setText("");
        baja.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstadoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alta;
    private javax.swing.JLabel baja;
    private javax.swing.JTextField boleto;
    private javax.swing.JButton btnVer;
    private javax.swing.JLabel cajon;
    private javax.swing.JLabel color;
    private javax.swing.JLabel entrada;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBaja;
    private javax.swing.JLabel lblBoleto;
    private javax.swing.JLabel lblCajon;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblEntrada;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPlacas;
    private javax.swing.JLabel lblPropietario;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblusuarioAlta;
    private javax.swing.JLabel lblusuarioBaja;
    private javax.swing.JLabel marca;
    private javax.swing.JLabel modelo;
    private javax.swing.JLabel placas;
    private javax.swing.JLabel propietario;
    private javax.swing.JLabel salida;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables

}
