package mx.com.object;

import mx.com.thread.HiloAlta;
import java.awt.Image;
import java.sql.Timestamp;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import mx.com.dao.CajonDAO;
import mx.com.model.Cajon;
import mx.com.model.Registro;
import mx.com.model.Usuario;
import mx.com.util.UtilidadSession;

/**
 *
 * @author abigail
 */

//ventana para el formulario de alta de autos
public class IngresoFrame extends javax.swing.JInternalFrame{

    Registro registro;//objeto de Registro
    Cajon cajonObj = new Cajon();// objeto de Cajon
    CajonDAO cajonDao = new CajonDAO();//objeto para hacer uso de los query para los cajones
    List<Cajon> listaCajones = cajonDao.getCajonesDisponibles(); //en una lista guardamos todos los cajones 
    DefaultComboBoxModel modeloCajon = new DefaultComboBoxModel(listaCajones.toArray()); //valores de la lista desplegable para el cajon
    
    
    /**
     * Creates new form Registro
     */
    public IngresoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblBoleto = new javax.swing.JLabel();
        boleto = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblPlacas = new javax.swing.JLabel();
        lblPropietario = new javax.swing.JLabel();
        lblCajon = new javax.swing.JLabel();
        lblEntrada = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        marca = new javax.swing.JTextField();
        placas = new javax.swing.JTextField();
        color = new javax.swing.JTextField();
        propietario = new javax.swing.JTextField();
        cajon = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        modelo = new javax.swing.JTextField();
        entrada = new javax.swing.JLabel();
        salida = new javax.swing.JLabel();
        lblAlta = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registro de Nuevo Auto");

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(204, 255, 204));
        lblTitulo.setText("Estacionamiento Santa Fe");

        lblBoleto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBoleto.setForeground(new java.awt.Color(255, 255, 255));
        lblBoleto.setText("No. Boleto:");

        boleto.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        boleto.setForeground(new java.awt.Color(204, 204, 255));
        boleto.setText("mostrado al imprimir boleto");

        lblMarca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMarca.setForeground(new java.awt.Color(255, 255, 255));
        lblMarca.setText("Marca:");

        lblModelo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblModelo.setForeground(new java.awt.Color(255, 255, 255));
        lblModelo.setText("Modelo:");

        lblColor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblColor.setForeground(new java.awt.Color(255, 255, 255));
        lblColor.setText("Color:");

        lblPlacas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPlacas.setForeground(new java.awt.Color(255, 255, 255));
        lblPlacas.setText("Placas:");

        lblPropietario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPropietario.setForeground(new java.awt.Color(255, 255, 255));
        lblPropietario.setText("Nombre del propietario:");

        lblCajon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCajon.setForeground(new java.awt.Color(255, 255, 255));
        lblCajon.setText("Cajon:");

        lblEntrada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEntrada.setForeground(new java.awt.Color(255, 255, 255));
        lblEntrada.setText("Fecha y hora de entrada:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fecha y hora de salida:");

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total:");

        total.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        total.setForeground(new java.awt.Color(204, 204, 255));
        total.setText("mostrado al dar baja");

        cajon.setModel(modeloCajon);

        btnRegistrar.setText("Registrar auto");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAuto(evt);
            }
        });

        entrada.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        entrada.setForeground(new java.awt.Color(204, 204, 255));
        entrada.setText("mostrado al imprimir boleto");

        salida.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        salida.setForeground(new java.awt.Color(204, 204, 255));
        salida.setText("mostrado al dar baja");

        lblAlta.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblAlta.setForeground(new java.awt.Color(255, 255, 204));
        lblAlta.setText("Alta de auto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(91, 91, 91))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPropietario)
                                .addGap(18, 18, 18)
                                .addComponent(propietario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEntrada)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblTotal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(total)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(entrada)
                                    .addComponent(salida)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCajon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cajon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblAlta)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblMarca)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblBoleto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(boleto))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblModelo)
                                            .addComponent(lblPlacas)
                                            .addComponent(lblColor))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(color)
                                            .addComponent(placas)
                                            .addComponent(modelo)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btnRegistrar)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAlta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBoleto)
                    .addComponent(boleto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelo)
                    .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlacas)
                    .addComponent(placas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColor)
                    .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPropietario)
                    .addComponent(propietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cajon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCajon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEntrada)
                    .addComponent(entrada))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(salida))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(total))
                .addGap(34, 34, 34)
                .addComponent(btnRegistrar)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //evento de accion para el boton "Registrar auto"
    private void btnRegistrarAuto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAuto
        if(verificarCampos()){ //se verifica que no deje campos vacios
            registro = new Registro();
            //establecemos en el objeto de registro los valores que ingresa el usuario
            registro.setMarca(marca.getText());
            registro.setModelo(modelo.getText());
            registro.setPlacas(placas.getText());
            registro.setColor(color.getText());
            registro.setPropietario(propietario.getText());
            registro.setCajon(cajon.getItemAt(cajon.getSelectedIndex()).getId());
            registro.setEntrada(new Timestamp(System.currentTimeMillis()));
            Usuario usuario = UtilidadSession.getInstance().getUsuario();//obtenemos el usuario en sesion
            registro.setUsuarioEntrada(usuario.getId());//se establece el usuario que dio la alta
            
            cajon.getItemAt(cajon.getSelectedIndex()).setEstado(true);//cambiamos a ocupado el cajon
            cajonDao.actualizarCajon(cajon.getItemAt(cajon.getSelectedIndex()));//se actualiza el estado del cajon

            //se abre hilo para el alta de auto
            HiloAlta hiloRegistro = new HiloAlta(registro);
            Thread hilo = new Thread(hiloRegistro);
            hilo.start();
        }else{
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos");//se ele informa que debe llenar todos los campos
        }
        
        limpiar();//se limpian los campos al dar la alta
        
    }//GEN-LAST:event_btnRegistrarAuto
    
    //metodo para limpiar campos
    private void limpiar(){
        marca.setText("");
        modelo.setText("");
        placas.setText("");
        color.setText("");
        propietario.setText("");
    }
    
    //metodo para verificar que los campos tengan valores
    private boolean verificarCampos(){
        boolean band = true;
        
        if(marca.getText().isEmpty() && 
           modelo.getText().isEmpty() && 
           placas.getText().isEmpty() && 
           color.getText().isEmpty() &&
           propietario.getText().isEmpty()){
                band = false;
        }
        return band;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel boleto;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<Cajon> cajon;
    private javax.swing.JTextField color;
    private javax.swing.JLabel entrada;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAlta;
    private javax.swing.JLabel lblBoleto;
    private javax.swing.JLabel lblCajon;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblEntrada;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPlacas;
    private javax.swing.JLabel lblPropietario;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField modelo;
    private javax.swing.JTextField placas;
    private javax.swing.JTextField propietario;
    private javax.swing.JLabel salida;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables

}
