package mx.com.object;

import mx.com.thread.HiloIngresar;
import mx.com.thread.HiloCajones;
import java.awt.Image;
import javax.swing.ImageIcon;
import mx.com.thread.HiloEgresar;

/**
 *
 * @author abigail
 */
//ventana para ofrecer el menu principal con diferentes opciones 
public class MenuPrincipal extends javax.swing.JFrame {

    /** Creates new form MenuPrincipal */
    public MenuPrincipal() {
        initComponents();
        //caracteristicas de la ventana
        setTitle("Estacionamiento Buena Fe");
        setLocationRelativeTo(null);
        ImageIcon icon = new ImageIcon("src/main/resources/cross.png"); //icono de la ventana
        Image image = icon.getImage();
        setIconImage(image); 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAlta = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnCajones = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnReporteSemanal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        btnAlta.setFont(new java.awt.Font("Sitka Small", 1, 11)); // NOI18N
        btnAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guardar.png"))); // NOI18N
        btnAlta.setText("Registro de Nuevo Auto");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaNuevoAuto(evt);
            }
        });

        btnUsuarios.setFont(new java.awt.Font("Sitka Small", 1, 11)); // NOI18N
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario.png"))); // NOI18N
        btnUsuarios.setText("Registro Usuarios");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarios(evt);
            }
        });

        btnCajones.setFont(new java.awt.Font("Sitka Small", 1, 11)); // NOI18N
        btnCajones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car.png"))); // NOI18N
        btnCajones.setText("Ver cajones");
        btnCajones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCajones(evt);
            }
        });

        btnBaja.setFont(new java.awt.Font("Sitka Small", 1, 11)); // NOI18N
        btnBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baja.png"))); // NOI18N
        btnBaja.setText("Entrega de Auto");
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaAuto(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Estacionamiento \"Buena Fé\"");

        btnCerrar.setFont(new java.awt.Font("Sitka Small", 0, 10)); // NOI18N
        btnCerrar.setText("Cerrar Sesion");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesion(evt);
            }
        });

        btnReporteSemanal.setFont(new java.awt.Font("Sitka Small", 1, 11)); // NOI18N
        btnReporteSemanal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivo.png"))); // NOI18N
        btnReporteSemanal.setText("Reporte semanal");
        btnReporteSemanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteSemanal(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCerrar))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReporteSemanal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCajones, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(btnBaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(52, 52, 52))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnCerrar)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCajones, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnReporteSemanal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //evento de accion para el boton "Registro de nuevo auto"
    private void btnAltaNuevoAuto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaNuevoAuto
        //se abre hilo para abrir una neuva ventana, lo cual nos permite abrir mas de una al mismo tiempo
        HiloIngresar hilo = new HiloIngresar();
        Thread nh = new Thread(hilo);//se crea el hilo
        nh.start();//comienza la ejecución del hilo
    }//GEN-LAST:event_btnAltaNuevoAuto

    //evento de accion para el boton "Ver cajones"
    private void btnVerCajones(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCajones
        //se abre hilo para abrir una neuva ventana, lo cual nos permite abrir mas de una al mismo tiempo
        HiloCajones hilo = new HiloCajones();
        Thread nh = new Thread(hilo);//se crea el hilo
        nh.start();//comienza la ejecución del hilo
    }//GEN-LAST:event_btnVerCajones

    //evento de accion para el boton "Entrega de auto"
    private void btnBajaAuto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaAuto
        //se abre hilo para abrir una neuva ventana, lo cual nos permite abrir mas de una al mismo tiempo
        HiloEgresar hilo = new HiloEgresar();
        Thread nh = new Thread(hilo);//se crea el hilo
        nh.start();//comienza la ejecución del hilo
    }//GEN-LAST:event_btnBajaAuto

    //evento de accion para el boton "Cerrar sesion"
    private void btnCerrarSesion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesion
        //volvemos a la ventana de inicio de sesion
        InicioSesionFrame inicio = new InicioSesionFrame();
        inicio.setVisible(true);
        this.dispose();//se cierra esta ventana
    }//GEN-LAST:event_btnCerrarSesion

    //evento de accion para el boton "Registro usuarios"
    private void btnUsuarios(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarios
        //se abre la venta del formulario para usuarios
        UsuarioFrame usuario = new UsuarioFrame();
        usuario.setVisible(true);
    }//GEN-LAST:event_btnUsuarios

    //evento de accion para el boton "Reporte semanal"
    private void btnReporteSemanal(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteSemanal
        //se abre la ventana del formulario de reportes
        ReporteFrame reporte = new ReporteFrame();
        reporte.setVisible(true);
    }//GEN-LAST:event_btnReporteSemanal

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnCajones;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnReporteSemanal;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
