package mx.com.object;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import mx.com.chat.ConexionServidor;
import mx.com.util.Constantes;

/**
 *
 * @author abigail
 */
public class ServidorFrame extends javax.swing.JInternalFrame {

    ConexionServidor servidor;
    private JFileChooser jFileChooser1 = new javax.swing.JFileChooser();//componente para elegir una ruta
    /**
     * Creates new form ClienteFrame
     */
    public ServidorFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIniciarServidor = new javax.swing.JButton();
        txtMensaje = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtVerMensaje = new javax.swing.JTextArea();
        btnCerrarServidor = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 153));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setMaximizable(true);
        setTitle("Servidor");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnIniciarServidor.setText("Iniciar Servidor");
        btnIniciarServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarServidorActionPerformed(evt);
            }
        });

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        txtVerMensaje.setColumns(20);
        txtVerMensaje.setRows(5);
        jScrollPane1.setViewportView(txtVerMensaje);

        btnCerrarServidor.setText("Desconectar Servidor");
        btnCerrarServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarServidorActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir chat");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnEnviar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIniciarServidor)
                        .addGap(18, 18, 18)
                        .addComponent(btnCerrarServidor)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnImprimir)
                .addGap(179, 179, 179))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciarServidor)
                    .addComponent(btnCerrarServidor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMensaje)
                    .addComponent(btnEnviar))
                .addGap(18, 18, 18)
                .addComponent(btnImprimir)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarServidorActionPerformed
        servidor = new ConexionServidor(".");
        servidor.start();
        JOptionPane.showMessageDialog(null, "¡Servidor conectado!");
    }//GEN-LAST:event_btnIniciarServidorActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        servidor.enviarMensaje(txtMensaje.getText());
        txtVerMensaje.setText(txtVerMensaje.getText()+"\n"+txtMensaje.getText());
        txtMensaje.setText("");
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnCerrarServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarServidorActionPerformed
        servidor.enviarMensaje(Constantes.CERRAR_SESION);
        btnEnviar.setEnabled(false);
        JOptionPane.showMessageDialog(null, "¡Servidor desconectado!");
    }//GEN-LAST:event_btnCerrarServidorActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
         //le damos a elegir donde guardar el archivo
        jFileChooser1.showSaveDialog(null);
        File archivo =jFileChooser1.getSelectedFile(); //aqui se almacena el nombre del archivo
        if(archivo !=null){//si se solicitó guardar un archivo
            String suffix = ".txt"; //variable para el sufijo
            //en caso de que no se asignó automáticamente el .pdf
            if(!jFileChooser1.getSelectedFile().getAbsolutePath().endsWith(suffix)){
                archivo = new File(jFileChooser1.getSelectedFile() + suffix); //se asigna a nuestro nombre el .pdf
            }
        }
        try{
            // Si el archivo no existe es creado
                if (!archivo.exists()) {
                    archivo.createNewFile();
                }

            FileWriter fw = new FileWriter(archivo);
            BufferedWriter bw = new BufferedWriter(fw);
            String contenido = txtVerMensaje.getText();
            bw.write(contenido);
            bw.close();  
        }catch(IOException e){
            e.printStackTrace();   
        } 
        JOptionPane.showMessageDialog(null, "Documento creado correctamente");//se informa que se ha creado el documento
    }//GEN-LAST:event_btnImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[]args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServidorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServidorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServidorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServidorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServidorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarServidor;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnIniciarServidor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtMensaje;
    public static javax.swing.JTextArea txtVerMensaje;
    // End of variables declaration//GEN-END:variables
}